
version: '3'

services:
  server:
    image: node:12.20.0-alpine3.10
    container_name: 'Server'
    volumes:
      - "./backend:/app"
    working_dir: /app
    environment:
      APP_SERVER_PORT: 5000
    ports:
      - "5000:5000"
      - "9229:9229"
    command: npm run server
    networks:
      - network

  client:
    image: node:12.20.0-alpine3.10
    container_name: 'Client'
    volumes:
      - "./client:/app"
    working_dir: /app
    environment:
      REACT_APP_PORT: 3000
    ports:
      - 80:3000
    command: npm run start
    networks:
      - network

  db:
    image: mysql:latest
    container_name: 'DB'
    restart: always
    environment:
      MYSQL_DATABASE: 'device_app_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_APP_PORT: 3306
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - "db:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - network

volumes:
  db:

networks:
  network:
    driver: bridge

